#!/bin/bash
#
# softnet - ...
#
# Copyright (C) 2013 Red Hat, Inc.
#
# Author: Masatake YAMATO <yamato@redhat.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

stat()
{
    local cpu
    local header_printed
    declare -a header=("processed" "dropped" "time_squeeze"
	"_a" "_b" "_c" "_d" "_e" "cpu_collision"
	"received_rps" "flow_limit_count"
	"REST")
    declare -a line
    declare -a tx
    declare -a rx
    local i
    local s

    while read -a line; do
	if [[ ${line[0]} = "NET_TX:" ]]; then
	    for (( i = 1; i < "${#line[@]}"; i++ )); do
		tx[$((i - 1))]=${line[$i]}
	    done
	elif [[ ${line[0]} = "NET_RX:" ]]; then
	    for (( i = 1; i < "${#line[@]}"; i++ )); do
		rx[$((i - 1))]=${line[$i]}
	    done
	fi
    done < /proc/softirqs

    for cpu in $(seq 0 $(( $(nproc) - 1))); do
	read -a line

	if [[ -z "$header_printed" ]]; then
	    header_printed=done

	    printf "%5s" cpu
	    printf "%12s" tx
	    printf "%12s" rx
	    for (( i = 0; i < "${#header[@]}"; i++ )); do
		if [[ -n "${line[$i]}" ]]; then
		    s="${header[$i]}"
		    if [[ ${s:0:1} != _ ]]; then
			printf "%18s" "$s"
		    fi
		else
		    break
		fi
	    done
	    echo
	fi

	printf "%5d" $cpu
	printf "%12d" ${tx[$cpu]}
	printf "%12s" ${rx[$cpu]}
	for (( i = 0; i < "${#line[@]}"; i++ )); do
	    s="${header[$i]}"
	    if [[ ${s:0:1} != _ ]]; then
		printf "%18d" "0x${line[$i]}"
	    fi
	done
	echo
    done < /proc/net/softnet_stat
}

main()
{
    stat
}

main
